[build]
  publish = "dist/flood-monitoring-app/browser"
  command = "ng build --configuration production"

[build.environment]
  NODE_VERSION = "20.18.0"
  NPM_VERSION = "10.8.2"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "no-referrer-when-downgrade"
    Content-Security-Policy = "default-src 'self' environment.data.gov.uk api.postcodes.io; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; font-src 'self' https://fonts.gstatic.com; img-src 'self' data: https://*; script-src 'self' 'unsafe-inline' 'unsafe-eval';"